# ~/.config/starship.toml
add_newline = true
format = "$directory$git_branch$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"
